---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pod-cost.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pod-cost.labels" . | nindent 4 }}
data:
  API_ENDPOINT: {{ .Values.config.apiEndpoint | quote }}
  COLLECTION_INTERVAL: {{ .Values.config.collectionInterval | quote }}
  CLUSTER_NAME: {{ .Values.config.clusterName | quote }}
  REGION: {{ .Values.config.region | quote }}
